package dominio;

// Generated 11-17-2014 08:01:24 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * Boletapagodescuento generated by hbm2java
 */
@Entity
@Table(name = "boletapagodescuento", catalog = "igf2014")
public class BoletaPagoDescuento implements java.io.Serializable {

	private int idBoletapagosdescuento;
	private TiposDescuentos tiposdescuentos;
	private BoletaPago boletaPago;
	private BigDecimal montoDescuento;
	private int usuarioCreador;
	private int usuarioModifica;
	private Date fechaCreacion;
	private Date fechaModifica;
	private int activo;

	public BoletaPagoDescuento() {
	}

	public BoletaPagoDescuento(int idBoletapagosdescuento,
			TiposDescuentos tiposdescuentos, BoletaPago boletapago,
			BigDecimal montoDescuento, int usuarioCreador, int usuarioModifica,
			Date fechaCreacion, Date fechaModifica, int activo) {
		this.idBoletapagosdescuento = idBoletapagosdescuento;
		this.tiposdescuentos = tiposdescuentos;
		this.boletaPago = boletaPago;
		this.montoDescuento = montoDescuento;
		this.usuarioCreador = usuarioCreador;
		this.usuarioModifica = usuarioModifica;
		this.fechaCreacion = fechaCreacion;
		this.fechaModifica = fechaModifica;
		this.activo = activo;
	}

	@Id
	@Column(name = "id_boletapagosdescuento", unique = true, nullable = false)
	public int getIdBoletapagosdescuento() {
		return this.idBoletapagosdescuento;
	}

	public void setIdBoletapagosdescuento(int idBoletapagosdescuento) {
		this.idBoletapagosdescuento = idBoletapagosdescuento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tiposdescuentos", nullable = false)
	public TiposDescuentos getTiposdescuentos() {
		return this.tiposdescuentos;
	}

	public void setTiposdescuentos(TiposDescuentos tiposdescuentos) {
		this.tiposdescuentos = tiposdescuentos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_boletapago", nullable = false)
	public BoletaPago getBoletapago() {
		return this.boletaPago;
	}

	public void setBoletapago(BoletaPago boletapago) {
		this.boletaPago = boletapago;
	}

	@Column(name = "monto_descuento", nullable = false, precision = 11)
	public BigDecimal getMontoDescuento() {
		return this.montoDescuento;
	}

	public void setMontoDescuento(BigDecimal montoDescuento) {
		this.montoDescuento = montoDescuento;
	}

	@Column(name = "usuario_creador", nullable = false)
	public int getUsuarioCreador() {
		return this.usuarioCreador;
	}

	public void setUsuarioCreador(int usuarioCreador) {
		this.usuarioCreador = usuarioCreador;
	}

	@Column(name = "usuario_modifica", nullable = false)
	public int getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(int usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", nullable = false, length = 19)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	@Column(name = "activo", nullable = false)
	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

}
