package dominio;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Boletapago generated by hbm2java
 */
@Entity
@Table(name = "boletapago", catalog = "igf2014", schema = "")
public class BoletaPago implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_boletapago", unique = true, nullable = false)
	private short idBoletapago;
	
	@Basic(optional = false)
	@Column(name = "periodo_pago", nullable = false, length = 25)
	private String periodoPago;
	
	@Basic(optional = false)
	@Column(name = "sueldo_pago", nullable = false, precision = 10)
	private BigDecimal sueldoPago;
	
	@Basic(optional = false)
	@Column(name = "id_empleado", nullable = false, length = 5)
	private String idEmpleado;
	
	@Basic(optional = false)
	@Column(name = "usuario_creador")
	private Integer usuarioCreador;
	
	@Basic(optional = false)
	@Column(name = "usuario_modifica")
	private Integer usuarioModifica;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Basic(optional = false)
	@Column(name = "fecha_creacion", length = 19)
	private Date fechaCreacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Basic(optional = false)
	@Column(name = "fecha_modifica", length = 19)
	private Date fechaModifica;
	
	@Basic(optional = false)
	@Column(name = "activo", nullable = false)
	private int activo;
	

	public BoletaPago() {
	}

	public BoletaPago(short idBoletapago, String periodoPago,
			BigDecimal sueldoPago, String idEmpleado, int activo) {
		this.idBoletapago = idBoletapago;
		this.periodoPago = periodoPago;
		this.sueldoPago = sueldoPago;
		this.idEmpleado = idEmpleado;
		this.activo = 1;
	}

	
	public short getIdBoletapago() {
		return this.idBoletapago;
	}

	public void setIdBoletapago(short idBoletapago) {
		this.idBoletapago = idBoletapago;
	}

	
	public String getPeriodoPago() {
		return this.periodoPago;
	}

	public void setPeriodoPago(String periodoPago) {
		this.periodoPago = periodoPago;
	}

	
	public BigDecimal getSueldoPago() {
		return this.sueldoPago;
	}

	public void setSueldoPago(BigDecimal sueldoPago) {
		this.sueldoPago = sueldoPago;
	}

	
	public String getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(String idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	
	public Integer getUsuarioCreador() {
		return this.usuarioCreador;
	}

	public void setUsuarioCreador(Integer usuarioCreador) {
		this.usuarioCreador = usuarioCreador;
	}

	
	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	
	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}
	/*
	 * 
	 * 
	 * this.boletaPagoDescuentos = boletaPagoDescuentos;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boletapago")
	private Set<BoletaPagoDescuento> boletaPagoDescuentos = new HashSet<BoletaPagoDescuento>(
			0);
	public Set<BoletaPagoDescuento> getBoletapagodescuentos() {
		return this.boletaPagoDescuentos;
	}

	public void setBoletapagodescuentos(
			Set<BoletaPagoDescuento> boletaPagoDescuentos) {
		this.boletaPagoDescuentos = boletaPagoDescuentos;
	}
	*/
}
