package dominio;

// Generated 11-10-2014 03:51:41 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Tiposdescuentos generated by hbm2java
 */
@Entity
@Table(name = "tiposdescuentos", catalog = "igf2014v2")
@NamedQueries({
	@NamedQuery(name = "daTipoDescuentoPorId", query = "from TiposDescuentos as tiposdescuentos where tiposdescuentos.idTiposdescuentos=:id_TiposDescuentos"),
	@NamedQuery(name = "buscarTodos", query = "from TiposDescuentos as tiposdescuentos"),
	
})
public class TiposDescuentos implements java.io.Serializable {

	@Id
	@Column(name = "id_tiposdescuentos", unique = true, nullable = false, length = 5)
	private String idTiposdescuentos;
	@Column(name = "descripcion", nullable = false, length = 250)
	private String descripcion;
	@Column(name = "porcentaje_descuento", nullable = false, precision = 5, scale = 3)
	private BigDecimal porcentajeDescuento;
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 10)
	private Date fechaIngreso;
	@Column(name = "id_usuario_creador")
	private Integer idUsuarioCreador;
	@Column(name = "id_usuario_modifica")
	private Integer idUsuarioModifica;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 19)
	private Date fechaCreacion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modifica", length = 19)
	private Date fechaModifica;
	@Column(name = "activo", nullable = false)
	private int activo;


	public TiposDescuentos() {
	}

	public TiposDescuentos(String idTiposdescuentos, String descripcion,
			BigDecimal porcentajeDescuento, Date fechaIngreso, int activo) {
		this.idTiposdescuentos = idTiposdescuentos;
		this.descripcion = descripcion;
		this.porcentajeDescuento = porcentajeDescuento;
		this.fechaIngreso = fechaIngreso;
		this.activo = activo;
	}

	public TiposDescuentos(String idTiposdescuentos, String descripcion,
			BigDecimal porcentajeDescuento, Date fechaIngreso,
			Integer idUsuarioCreador, Integer idUsuarioModifica,
			Date fechaCreacion, Date fechaModifica, int activo,
			Set<BoletaPagoDescuento> boletaPagoDescuentos) {
		this.idTiposdescuentos = idTiposdescuentos;
		this.descripcion = descripcion;
		this.porcentajeDescuento = porcentajeDescuento;
		this.fechaIngreso = fechaIngreso;
		this.idUsuarioCreador = idUsuarioCreador;
		this.idUsuarioModifica = idUsuarioModifica;
		this.fechaCreacion = fechaCreacion;
		this.fechaModifica = fechaModifica;
		this.activo = activo;
		
	}


	public String getIdTiposdescuentos() {
		return this.idTiposdescuentos;
	}

	public void setIdTiposdescuentos(String idTiposdescuentos) {
		this.idTiposdescuentos = idTiposdescuentos;
	}

	
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	
	public BigDecimal getPorcentajeDescuento() {
		return this.porcentajeDescuento;
	}

	public void setPorcentajeDescuento(BigDecimal porcentajeDescuento) {
		this.porcentajeDescuento = porcentajeDescuento;
	}


	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	
	public Integer getIdUsuarioCreador() {
		return this.idUsuarioCreador;
	}

	public void setIdUsuarioCreador(Integer idUsuarioCreador) {
		this.idUsuarioCreador = idUsuarioCreador;
	}

	
	public Integer getIdUsuarioModifica() {
		return this.idUsuarioModifica;
	}

	public void setIdUsuarioModifica(Integer idUsuarioModifica) {
		this.idUsuarioModifica = idUsuarioModifica;
	}

	
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	
	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}
    /*
     * this.boletaPagoDescuentos = boletaPagoDescuentos;
     * 
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposdescuentos")
	private Set<BoletaPagoDescuento> boletaPagoDescuentos = new HashSet<BoletaPagoDescuento>(
			0);
	
	public Set<BoletaPagoDescuento> getBoletapagodescuentos() {
		return this.boletaPagoDescuentos;
	}

	public void setBoletapagodescuentos(
			Set<BoletaPagoDescuento> boletaPagoDescuentos) {
		this.boletaPagoDescuentos = boletaPagoDescuentos;
	}*/

}
